version: '3.9'

services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html:delegated
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
    volumes:
      - db_data:/var/lib/mysql

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html

volumes:
  db_data:
